#ifndef MINIMUX_H
#define MINIMUX_H

/* Generated by tools/gen-c-header.zig. Do not edit by hand. */

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
#define MINIMUX_PROTOCOL_VERSION "0.1.0"
#define MINIMUX_METHOD_COUNT 15
#define MINIMUX_ERROR_CODE_COUNT 14

typedef struct minimux_session minimux_session_t;
typedef struct minimux_session_list minimux_session_list_t;
typedef struct minimux_pane minimux_pane_t;
typedef struct minimux_snapshot minimux_snapshot_t;
typedef struct minimux_recording minimux_recording_t;
typedef struct minimux_tap minimux_tap_t;

struct minimux_session_options {
    uint32_t flags;
};

struct minimux_pane_size {
    uint16_t cols;
    uint16_t rows;
};

struct minimux_pane_create_options {
    const char *const *argv;
    size_t argv_len;
    const char *const *env;
    size_t env_len;
    const char *cwd;
    struct minimux_pane_size size;
};

struct minimux_record_policy {
    uint32_t flags;
};

struct minimux_tap_filter {
    uint32_t flags;
};
#define MINIMUX_ERROR_PARSE_ERROR -32700
#define MINIMUX_ERROR_INVALID_REQUEST -32600
#define MINIMUX_ERROR_METHOD_NOT_FOUND -32601
#define MINIMUX_ERROR_INVALID_PARAMS -32602
#define MINIMUX_ERROR_INTERNAL_ERROR -32603
#define MINIMUX_ERROR_SESSION_NOT_FOUND 1001
#define MINIMUX_ERROR_DAEMON_NOT_RUNNING 1002
#define MINIMUX_ERROR_CONTROL_SOCKET_UNAVAILABLE 1003
#define MINIMUX_ERROR_CONTROL_SOCKET_TIMEOUT 1004
#define MINIMUX_ERROR_VALIDATION_UNKNOWN_REQUIRED_FIELD 2001
#define MINIMUX_ERROR_VALIDATION_INVALID_ENUM_VALUE 2002
#define MINIMUX_ERROR_VALIDATION_NON_MONOTONIC_SEQUENCE 2003
#define MINIMUX_ERROR_VALIDATION_MISSING_METHOD 2004
#define MINIMUX_ERROR_VALIDATION_MISSING_ERROR_CODE 2005

/* session: On success, *out_session is caller-owned and must be released with minimux_session_destroy. */
int minimux_session_create(const char *name, const struct minimux_session_options *options, minimux_session_t **out_session);

/* session: On success, *out_session is caller-owned and must be released with minimux_session_destroy. */
int minimux_session_attach(const char *name, minimux_session_t **out_session);

/* session: On success, *out_list is caller-owned and must be released with minimux_session_list_destroy. */
int minimux_session_list(minimux_session_list_t **out_list);

/* session: Releases a caller-owned session list; NULL is accepted. */
void minimux_session_list_destroy(minimux_session_list_t *list);

/* session: The name pointer is borrowed for the duration of the call. */
int minimux_session_terminate(const char *name);

/* session: Releases a caller-owned session handle; NULL is accepted. */
void minimux_session_destroy(minimux_session_t *session);

/* pane: The session and options pointers are borrowed; *out_pane is caller-owned on success. */
int minimux_pane_create(minimux_session_t *session, const struct minimux_pane_create_options *options, minimux_pane_t **out_pane);

/* pane: The pane and byte buffer are borrowed for the duration of the call. */
int minimux_pane_send(minimux_pane_t *pane, const uint8_t *bytes, size_t len);

/* pane: The pane pointer is borrowed for the duration of the call. */
int minimux_pane_resize(minimux_pane_t *pane, uint16_t cols, uint16_t rows);

/* snapshot: On success, *out_snapshot is caller-owned and must be released with minimux_snapshot_destroy. */
int minimux_pane_snapshot(minimux_pane_t *pane, minimux_snapshot_t **out_snapshot);

/* pane: The pane pointer is borrowed; closing does not free the handle. */
int minimux_pane_close(minimux_pane_t *pane);

/* pane: Releases a caller-owned pane handle; NULL is accepted. */
void minimux_pane_destroy(minimux_pane_t *pane);

/* agent: The pane and harness pointers are borrowed for the duration of the call. */
int minimux_agent_wait_idle(minimux_pane_t *pane, uint64_t timeout_ms, const char *harness);

/* snapshot: Releases a caller-owned snapshot; NULL is accepted. */
void minimux_snapshot_destroy(minimux_snapshot_t *snapshot);

/* recording: The pane, path, and policy are borrowed; *out_recording is caller-owned on success. */
int minimux_record_start(minimux_pane_t *pane, const char *path, const struct minimux_record_policy *policy, minimux_recording_t **out_recording);

/* recording: The recording pointer is borrowed; stopping does not free the handle. */
int minimux_record_stop(minimux_recording_t *recording);

/* recording: Releases a caller-owned recording handle; NULL is accepted. */
void minimux_recording_destroy(minimux_recording_t *recording);

/* tap: The pane and filter are borrowed; *out_tap is caller-owned on success. */
int minimux_tap_open(minimux_pane_t *pane, const struct minimux_tap_filter *filter, minimux_tap_t **out_tap);

/* tap: The tap pointer is borrowed; closing does not free the handle. */
int minimux_tap_close(minimux_tap_t *tap);

/* tap: Releases a caller-owned tap handle; NULL is accepted. */
void minimux_tap_destroy(minimux_tap_t *tap);

/* system: The caller owns the output buffer and passes its byte length. */
int minimux_system_health(char *buffer, size_t len);

#ifdef __cplusplus
}
#endif

#endif /* MINIMUX_H */
