const std = @import("std");
const proto = @import("minimux_proto");

const HeaderError = error{
    MissingOutputPath,
};

pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len < 2) return error.MissingOutputPath;
    const output_path = args[1];

    var output: std.Io.Writer.Allocating = .init(std.heap.smp_allocator);
    defer output.deinit();
    const writer = &output.writer;

    try writer.writeAll(
        \\#ifndef MINIMUX_H
        \\#define MINIMUX_H
        \\
        \\/* Generated by tools/gen-c-header.zig. Do not edit by hand. */
        \\
        \\#include <stddef.h>
        \\#include <stdint.h>
        \\
        \\#ifdef __cplusplus
        \\extern "C" {
        \\#endif
        \\
    );

    try writer.print(
        \\#define MINIMUX_PROTOCOL_VERSION "{s}"
        \\#define MINIMUX_METHOD_COUNT {d}
        \\#define MINIMUX_ERROR_CODE_COUNT {d}
        \\
        \\
    , .{ proto.protocol_version, proto.public_methods.len, proto.error_codes.len });

    try writer.writeAll(
        \\typedef struct minimux_session minimux_session_t;
        \\typedef struct minimux_session_list minimux_session_list_t;
        \\typedef struct minimux_pane minimux_pane_t;
        \\typedef struct minimux_snapshot minimux_snapshot_t;
        \\typedef struct minimux_recording minimux_recording_t;
        \\typedef struct minimux_tap minimux_tap_t;
        \\
        \\struct minimux_session_options {
        \\    uint32_t flags;
        \\};
        \\
        \\struct minimux_pane_size {
        \\    uint16_t cols;
        \\    uint16_t rows;
        \\};
        \\
        \\struct minimux_pane_create_options {
        \\    const char *const *argv;
        \\    size_t argv_len;
        \\    const char *const *env;
        \\    size_t env_len;
        \\    const char *cwd;
        \\    struct minimux_pane_size size;
        \\};
        \\
        \\struct minimux_record_policy {
        \\    uint32_t flags;
        \\};
        \\
        \\struct minimux_tap_filter {
        \\    uint32_t flags;
        \\};
        \\
    );

    for (proto.error_codes) |entry| {
        try writer.writeAll("#define MINIMUX_ERROR_");
        try writeUpperSnake(writer, entry.name);
        try writer.print(" {d}\n", .{entry.code});
    }
    try writer.writeByte('\n');

    for (proto.c_api_operations) |operation| {
        try writer.print("/* {s}: {s} */\n{s}\n\n", .{ operation.group, operation.ownership, operation.signature });
    }

    try writer.writeAll(
        \\#ifdef __cplusplus
        \\}
        \\#endif
        \\
        \\#endif /* MINIMUX_H */
        \\
    );

    try std.Io.Dir.cwd().writeFile(init.io, .{
        .sub_path = output_path,
        .data = output.written(),
    });
}

test "generated header metadata is non-empty" {
    try std.testing.expect(proto.c_api_operations.len >= 15);
    try std.testing.expect(proto.error_codes.len >= 10);
}

fn writeUpperSnake(writer: *std.Io.Writer, value: []const u8) !void {
    for (value) |byte| {
        try writer.writeByte(std.ascii.toUpper(byte));
    }
}
